import Head from "next/head";
import Layout from "../components/Layout";
import Body from "../components/Body"
import Advert from "../components/Advert"
import Services from "../components/Services"
import Strength from "../components/Strength";
import Testimonial from "../components/Testimonial";

export default function Home() {
  return (
    <Layout>
      <div>
        <Head>
          <title>PIZZA</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <Body/>   
          <Advert/>
          <Services/>   
          <Strength/>  
          <Testimonial/>
        </main>
      </div>
      </Layout>
  );
}

