import Head from "next/head";
import Layout from "../components/Layout";
import sp1 from "../components/sp1"

export default function singleProduct1() {
  return (
    <Layout>
      <div>
        <Head>
          <title>PIZZA</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
            
        
        </main>
      </div>
      </Layout>
  );
}

