import styles from "../../styles/singleProduct.module.css";
import css from "../../styles/singleProduct.module.css";
import Image from "next/image";
import p1 from '../../assets/p1.jpg'
import { useState } from "react";
import link from "next/link";
import Head from "next/head";
import Layout from "../../components/Layout";



const Product = () => {
  const [size, setSize] = useState(0);
  const pizza = {
    id: 1, 
    img: "/img/pizza.png",
    name: "This is burger pizza",
    price: [19.9, 23.9, 27.9],
    desc: "Chicken, Lunch, Pizza, Burger",
  };

  return (
    <Layout>
    <div>
      <Head>
        <title>PIZZA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      {/* body */}
      <main>
          
    <div className={styles.container}>
      <div className={styles.left}>
        <div className={styles.imgContainer}>
          <Image src={p1} objectFit="contain" layout="fill" alt="" />
        </div>
      </div>
      <div className={styles.right}>
        <div className={styles.title}>{pizza.name}
        </div>
       
        <span className={styles.price}></span>
        <p className={styles.desc}>{pizza.desc}</p>
        <span>Tags: Healthy, organic Chicken Sauce</span>
        <h5 className={styles.choose}>Choose Pizza size</h5>
        <div className={styles.sizes}>
          <div className={styles.size} onClick={() => setSize(0)}>
            <Image src="/img/size.png" layout="fill" alt="" />
            <span className={styles.number}>Small</span>
          </div>
          <div className={styles.size} onClick={() => setSize(1)}>
            <Image src="/img/size.png" layout="fill" alt="" />
            <span className={styles.number}>Medium</span>
          </div>
          <div className={styles.size} onClick={() => setSize(2)}>
            <Image src="/img/size.png" layout="fill" alt="" />
            <span className={styles.number}>Large</span>
          </div>
        </div>
        <h5 className={styles.choose}>Choose additional ingredients</h5>
        <div className={styles.ingredients}>
          
          <div className={styles.option}>
            <input
              className={styles.checkbox}
              type="checkbox"
              id="Sauce"
              name="Sauce"
            />
            <label htmlFor="garlic">Sauce</label>
          </div>
        </div>
        <div className={styles.add}>
            <input type="number" defaultValue={1} className={styles.quantity}/>
            <button className={`btn ${css.btn}`}>Add to Cart</button>
        </div>
      </div>
    </div>
    </main>
      </div>
      </Layout>
  );
};

export default Product;